---
title: "git_00"
author: "graciela Orozco"
date: "Spring semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

 

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

 "You are old, father William," the young man said,  
    "And your hair has become very white;  
  And yet you incessantly stand on your head —  
    Do you think, at your age, it is right?"  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

The buzz saw snarled and rattled in the yard  
And made dust and dropped stove-length sticks of wood,  
Sweet-scented stuff when the breeze drew across it.  
And from there those that lifted eyes could count  
Five mountain ranges one behind the other  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

From childhood’s hour I have not been  
As others were—I have not seen  
As others saw—I could not bring  
My passions from a common spring—  
From the same source I have not taken  
My sorrow—I could not awaken  
My heart to joy at the same tone—  
And all I lov’d—I lov’d alone—  


